#!/bin/bash
#------------------------------------------------------------------------------
# FILE:         setup-apt-proxy.sh
# CONTRIBUTOR:  Jeff Lill
# COPYRIGHT:    Copyright (c) 2016-2017 by NeonForge, LLC.  All rights reserved.
#
# Have this node use the APT package cache server if one was specified.

# Configure Bash strict mode so that the entire script will fail if 
# any of the commands fail.
#
#       http://redsymbol.net/articles/unofficial-bash-strict-mode/
#
# NOTE: I'm not using [-u] here to avoid failing for undefined
#       environment variables because some won't be initialized
#       when prepping nodes without a full cluster definition.

set -eo pipefail

echo
echo "**********************************************" 1>&2
echo "** SETUP-APT-PROXY                          **" 1>&2
echo "**********************************************" 1>&2

# Load the cluster configuration and setup utilities.

. $<load-cluster-config>
. setup-utility.sh

# Configure the cache.

if [ "${NEON_APT_CACHE}" != "" ] ; then

    cat <<EOF > /etc/apt/apt.conf.d/02proxy
//-----------------------------------------------------------------------------
// FILE:        /etc/apt/apt.conf.d/02proxy
// CONTRIBUTOR: Generated by [neon-cli] during cluster setup.
//
// This file configures APT on the local machine to proxy requests through the
// [apt-cacher-ng] service at the URL specified by ${NEON_APT_CACHE}.  Presumably,
// this cache is running on the local network which can dramatically reduce
// external network traffic to the APT mirrors and improve cluster setup and
// upgrade performance.

Acquire::http::proxy "${NEON_APT_CACHE}";
EOF

fi
