//-----------------------------------------------------------------------------
// FILE:	    Startup.cs
// CONTRIBUTOR: Marcus Bowyer, Jeff Lill
// COPYRIGHT:   Copyright (c) 2005-2021 by neonFORGE LLC.  All rights reserved.

using System;

using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;

using KubeOps.Operator;

namespace NeonClusterOperator
{
    /// <summary>
    /// Configures the operator's service controllers.
    /// </summary>
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            // $note(jefflill):
            //
            // We need to manually add the entities from the [Neon.Kube.Resources]
            // assembly so ALL CRDs will be generated by KubeOps.

            services.AddKubernetesOperator()
                .AddResourceAssembly(typeof(Neon.Kube.Entities.V1ContainerRegistry).Assembly);
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseKubernetesOperator();
        }
    }
}
