#!/bin/bash
#------------------------------------------------------------------------------
# FILE:         setup-apt-proxy.sh
# CONTRIBUTOR:  Jeff Lill
# COPYRIGHT:    Copyright (c) 2016-2018 by neonFORGE, LLC.  All rights reserved.
#
# Have this node use the APT package cache server if one was specified.

# Configure Bash strict mode so that the entire script will fail if 
# any of the commands fail.
#
#       http://redsymbol.net/articles/unofficial-bash-strict-mode/
#
# NOTE: I'm not using [-u] here to avoid failing for undefined
#       environment variables because some won't be initialized
#       when prepping nodes without a full hive definition.

set -eo pipefail

echo
echo "**********************************************" 1>&2
echo "** SETUP-APT-PROXY                          **" 1>&2
echo "**********************************************" 1>&2

# Load the hive configuration and setup utilities.

. $<load-hive-conf>
. setup-utility.sh

# Install the [apt-cacher-ng] service on manager nodes.

if [ "${NEON_NODE_ROLE}" == "manager" ] ; then

	set -eou pipefail	# Enable full failure detection

	safe-apt-get update
	safe-apt-get install -yq apt-cacher-ng

	# Configure the cache to pass-thru SSL requests
	# and then restart.

	echo "PassThroughPattern:^.*:443$" >> /etc/apt-cacher-ng/acng.conf
	systemctl restart apt-cacher-ng

	set -eo pipefail	# Revert back to partial failure detection

	# Give the proxy service a chance to start.

	sleep 5
fi

# Configure APT proxy selection.

cat <<EOF > ${NEON_BIN_FOLDER}/apt-proxy-detect
#------------------------------------------------------------------------------
# FILE:        ${NEON_BIN_FOLDER}/apt-proxy-detect
# CONTRIBUTOR: Generated by [neon-cli] during hive setup.
#
# This script determine which (if any) configured APT proxy caches are running
# and returns its URL or "DIRECT" if none of the proxies are available and the
# distribution's mirror should be accessed directly.
#
# This is called when the following is specified in the APT configuration,
# as we do further below:
#
#		Acquire::http::ProxyAutoDetect "${NEON_BIN_FOLDER}/apt-proxy-detect";
#
# See this link for more information:
#
#		https://trent.utfs.org/wiki/Apt-get#Failover_Proxy

for proxy in \${NEON_APT_PROXY}; do
	if nc -w1 -z \${proxy/:/ }; then
		echo http://\${proxy}
		exit
	fi
done
echo "DIRECT"
EOF

chmod 771 ${NEON_BIN_FOLDER}/apt-proxy-detect

if [ "${NEON_APT_PROXY}" != "" ] ; then

    cat <<EOF > /etc/apt/apt.conf.d/02proxy
//-----------------------------------------------------------------------------
// FILE:        /etc/apt/apt.conf.d/02proxy
// CONTRIBUTOR: Generated by [neon-cli] during hive setup.
//
// This file configures APT on the local machine to proxy requests through the
// [apt-cacher-ng] service at the URL specified by ${NEON_APT_PROXY}.  Presumably,
// this cache is running on the local network which can dramatically reduce
// external network traffic to the APT mirrors and improve hive setup and
// update performance.

Acquire::http::ProxyAutoDetect "${NEON_BIN_FOLDER}/apt-proxy-detect";
EOF
else
    echo > /etc/apt/apt.conf.d/02proxy
fi
