//-----------------------------------------------------------------------------
// FILE:	    WebHelper.Extensions.cs
// CONTRIBUTOR: Jeff Lill
// COPYRIGHT:	Copyright (c) 2016-2019 by neonFORGE, LLC.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Diagnostics.Contracts;
using System.IO;
using System.Linq;
using System.Threading;

using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Controllers;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

using Neon.Common;
using Neon.Data;
using Neon.Diagnostics;

namespace Neon.Web
{
    public static partial class WebHelper
    {
        //---------------------------------------------------------------------
        // Microsoft.AspNetCore.Http.HttpRequest extensions.

        /// <summary>
        /// Returns the full URI for an <see cref="HttpRequest"/> (not including the port number).
        /// </summary>
        /// <param name="request">The request.</param>
        /// <returns>The fully qualified URI including any query parameters.</returns>
        public static string GetUri(this HttpRequest request)
        {
            return $"{request.Scheme}://{request.Host}{request.Path}{request.QueryString}";
        }

        /// <summary>
        /// Returns the source IP address for an HTTP request.
        /// </summary>
        /// <param name="request">The request.</param>
        /// <returns>The source IP address (as a string) or <c>null</c> if this couldn't be determined.</returns>
        private static string GetSourceAddress(this HttpRequest request)
        {
            string address = null;

            if (request.Headers.TryGetValue("X-Forwarded-For", out var forwardedFor))
            {
                if (forwardedFor.Count > 0)
                {
                    address = forwardedFor.First();
                }
            }

            if (address == null)
            {
                address = request.HttpContext.Connection.RemoteIpAddress.ToString();
            }

            return address;
        }
        
        //---------------------------------------------------------------------
        // IMvcBuilder extensions

        /// <summary>
        /// Adds the services from an <see cref="IServiceContainer"/> to the <see cref="IServiceCollection"/>.
        /// This is commonly used when configuring services for an ASP.NET application pipeline.  The method
        /// also enables response compression by default.
        /// </summary>
        /// <param name="builder">The target <see cref="IMvcBuilder"/>.</param>
        /// <param name="source">The service source container or <c>null</c> to copy from <see cref="NeonHelper.ServiceContainer"/>.</param>
        /// <param name="disableResponseCompression">Optionally disable response compression.</param>
        /// <returns>The <paramref name="builder"/>.</returns>
        public static IMvcBuilder AddNeon(
            IMvcBuilder         builder, 
            IServiceContainer   source = null,
            bool                disableResponseCompression = false)
        {
            Covenant.Requires<ArgumentNullException>(builder != null);

            source = source ?? NeonHelper.ServiceContainer;

            foreach (var service in source)
            {
                builder.Services.Add(service);
            }

            if (!disableResponseCompression)
            {
                builder.Services.AddResponseCompression();
            }

            return builder;
        }

        //---------------------------------------------------------------------
        // IMvcBuilder extensions

        /// <summary>
        /// Performs Neon related initialization including adding the the <see cref="RoundTripJsonInputFormatter"/>,
        /// <see cref="RoundTripJsonOutputFormatter"/> and <b>Newtonsoft JSON</b> formatters to the
        /// request pipeline.  These handle serialization and deserailzation of JSON text submitted to and
        /// returned from web services and classes generated by <b>Neon.CodeGen</b> implementing 
        /// <see cref="IRoundtripData"/> as well as many basic .NET types.
        /// </summary>
        /// <param name="builder">The MVC builder.</param>
        /// <param name="disableRoundTripFormatters">Optionally disable adding the round-trip formatters.</param>
        /// <param name="allowRoundtripFormatter">
        /// Optional lamda function that can be used to customize which types allowed
        /// to be handled by the custom round-trip formatters.  When this is <c>null</c>, 
        /// all types will be handled by the formatters, otherwise only those types
        /// where this function returns <c>true</c> will be handled by the custom formatters.
        /// Other types will be passed on to the remaining formatters.
        /// </param>
        /// <returns>The <paramref name="builder"/>.</returns>
        /// <remarks>
        /// <para>
        /// This provides both backwards and forwards data compatibility on both the client and service
        /// side by retaining object properties that one side or the other doesn't know about.  This enables
        /// scenarios where new properties are added to a data object but the solution components aren't
        /// all upgraded at the same time as a monolithic app.
        /// </para>
        /// </remarks>
        public static IMvcBuilder AddNeon(
            this IMvcBuilder    builder, 
            bool                disableRoundTripFormatters  = false, 
            Func<Type, bool>    allowRoundtripFormatter     = null)
        {
            if (!disableRoundTripFormatters)
            {
                builder.AddMvcOptions(
                    options =>
                    {
                        options.InputFormatters.Insert(0, new RoundTripJsonInputFormatter(allowRoundtripFormatter));
                        options.OutputFormatters.Insert(0, new RoundTripJsonOutputFormatter(allowRoundtripFormatter));
                    });
            }

            return builder;
        }
    }
}
