//-----------------------------------------------------------------------------
// FILE:	    WebHelper.Extensions.cs
// CONTRIBUTOR: Jeff Lill
// COPYRIGHT:	Copyright (c) 2016-2019 by neonFORGE, LLC.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Diagnostics.Contracts;
using System.IO;
using System.Threading;

using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Controllers;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

using Neon.Common;
using Neon.Data;
using Neon.Diagnostics;

namespace Neon.Web
{
    public static partial class WebHelper
    {
        //---------------------------------------------------------------------
        // IServiceCollection extensions

        /// <summary>
        /// Adds the services from an <see cref="IServiceContainer"/> to the <see cref="IServiceCollection"/>.
        /// This is commonly used when configuring services for an ASP.NET application pipeline.
        /// </summary>
        /// <param name="services">The target service collection.</param>
        /// <param name="source">The service source container or <c>null</c> to copy from <see cref="NeonHelper.ServiceContainer"/>.</param>
        public static void AddNeon(this IServiceCollection services, IServiceContainer source = null)
        {
            source = source ?? NeonHelper.ServiceContainer;

            foreach (var service in source)
            {
                services.Add(service);
            }
        }

        //---------------------------------------------------------------------
        // IApplicationBuilder extensions

        /// <summary>
        /// Adds default Neon functionality to the <see cref="IApplicationBuilder"/>
        /// HTTP request pipeline.
        /// </summary>
        /// <param name="app">The application pipeline builder.</param>
        /// <param name="loggerFactory">The application logger factory.</param>
        /// <returns>The <pararef name="app"/>.</returns>
        /// <remarks>
        /// <para>
        /// This method adds the following capabilities:
        /// </para>
        /// <list type="bullet">
        ///     <item>
        ///     Sets the pipeline's <see cref="IApplicationBuilder.ApplicationServices"/> dependency injection
        ///     container to <see cref="NeonHelper.ServiceContainer"/>, the default Neon root container.
        ///     </item>
        /// </list>
        /// </remarks>
        public static IApplicationBuilder UseNeon(this IApplicationBuilder app, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddProvider(app.ApplicationServices.GetService<ILoggerProvider>());

            return app;
        }

        //---------------------------------------------------------------------
        // Microsoft.AspNetCore.Http.HttpRequest extensions.

        /// <summary>
        /// Returns the full URI for an <see cref="HttpRequest"/> (not including the port number).
        /// </summary>
        /// <param name="request">The request.</param>
        /// <returns>The fully qualified URI including any query parameters.</returns>
        public static string GetUri(this HttpRequest request)
        {
            return $"{request.Scheme}://{request.Host}{request.Path}{request.QueryString}";
        }

        //---------------------------------------------------------------------
        // MvcOptions extensions

        /// <summary>
        /// Adds the <see cref="RoundTripJsonInputFormatter"/> and <see cref="RoundTripJsonOutputFormatter"/>
        /// formatters to the request pipeline.  These handle serialization and deserailzation of
        /// JSON text submitted to and returned from web services and classes generated by <b>Neon.CodeGen</b>
        /// implementing <see cref="IGeneratedType"/> as well as many basic .NET types.
        /// </summary>
        /// <param name="options">The MVC options.</param>
        /// <remarks>
        /// <para>
        /// This provides both backwards and forwards data compatibility on both the client and service
        /// side by retaining object properties that one side or the other doesn't know about.  This enables
        /// scenarios where new properties are added to a data object but the solution components aren't
        /// all upgraded at the same time as a monolithic app.
        /// </para>
        /// <para>
        /// This is simply a shortcut for the following MVC service configuration code:
        /// </para>
        /// <code language="C#">
        /// services.AddMvc(
        ///     options =>
        ///     {
        ///         options.InputFormatters.Insert(0, new RoundTripJsonInputFormatter());
        ///         options.OutputFormatters.Insert(0, new RoundTripJsonOutputFormatter());
        ///     });
        /// </code>
        /// </remarks>
        public static void AddNeonRoundTripJsonFormatters(this MvcOptions options)
        {
            options.InputFormatters.Insert(0, new RoundTripJsonInputFormatter());
            options.OutputFormatters.Insert(0, new RoundTripJsonOutputFormatter());
        }
    }
}
