const defaultTheme = require('tailwindcss/defaultTheme')
const colors = require('tailwindcss/colors')


module.exports = {
    content: [
        "./AppState/**/*.{razor,razor.cs,razor.css,html,js,cshtml}",
        "./Data/**/*.{razor,razor.cs,razor.css,html,js,cshtml}",
        "./Pages/**/*.{razor,razor.cs,razor.css,html,js,cshtml}",
        "./Shared/**/*.{razor,razor.cs,razor.css,html,js,cshtml}"
    ],
    theme: {
        colors: {
            transparent: 'transparent',
            current: 'currentColor',
            'bg': 'var(--c-bg)',
            'bg-dark': 'var(--c-bg-dark)',
            'card': 'var(--c-card)',
            slate: colors.slate

        },
        fontFamily: {
            'sans': ['Pangram Sans', ...defaultTheme.fontFamily.sans],
            'mono': [...defaultTheme.fontFamily.mono]
        },
        fontSize: {
            '0': 'var(--f0)',
            '1': 'var(--f1)',
            '2': 'var(--f2)',
            '3': 'var(--f3)',
            'base': 'var(--f3)',
            '4': 'var(--f4)',
            '5': 'var(--f5)',
            '6': 'var(--f6)',
            '7': 'var(--f7)',
            '8': 'var(--f8)',
            '9': 'var(--f9)',
            '10': 'var(--f10)',
            '11': 'var(--f11)',
            '12': 'var(--f12)',
            '13': 'var(--f13)',
            '14': 'var(--f14)',
            '15': 'var(--f15)',
            '16': 'var(--f16)',
            '20': 'calc(var(--f10) * 2)',
            '24': 'calc(var(--f12) * 2)',
            '32': 'calc(var(--f16) * 2)',
            '48': 'calc(var(--f16) * 3)',
            '64': 'calc(var(--f16) * 4)',
            '80': 'calc(var(--f16) * 5)',
            '96': 'calc(var(--f16) * 6)',
        },
        //spacing scale is HALF of fontsize, bc it usually comes in pairs eg (right/left padding), (top/bottom padding)
        padding: {
            '0': 0,
            '0.5': 'calc(var(--f0) / 2)',
            '1': 'calc(var(--f1) / 2)',
            '2': 'calc(var(--f2) / 2)',
            '3': 'calc(var(--f3) / 2)',
            '4': 'calc(var(--f4) / 2)',
            '5': 'calc(var(--f5) / 2)',
            '6': 'calc(var(--f6) / 2)',
            '7': 'calc(var(--f7) / 2)',
            '8': 'calc(var(--f8) / 2)',
            '9': 'calc(var(--f9) / 2)',
            '10': 'calc(var(--f10) / 2)',
            '11': 'calc(var(--f11) / 2)',
            '12': 'calc(var(--f12) / 2)',
            '13': 'calc(var(--f13) / 2)',
            '14': 'calc(var(--f14) / 2)',
            '15': 'calc(var(--f15) / 2)',
            '16': 'calc(var(--f16) / 2)',
            '20': 'var(--f10)',
            '24': 'var(--f12)',
            '32': 'var(--f16)',
            '48': 'calc(var(--f16) * 2)',
            '64': 'calc(var(--f16) * 3)',
            '80': 'calc(var(--f16) * 4)',
            '96': 'calc(var(--f16) * 5)',
        },
        margin: {
            '0': 0,
            '0.5': 'calc(var(--f0) / 2)',
            '1': 'calc(var(--f1) / 2)',
            '2': 'calc(var(--f2) / 2)',
            '3': 'calc(var(--f3) / 2)',
            '4': 'calc(var(--f4) / 2)',
            '5': 'calc(var(--f5) / 2)',
            '6': 'calc(var(--f6) / 2)',
            '7': 'calc(var(--f7) / 2)',
            '8': 'calc(var(--f8) / 2)',
            '9': 'calc(var(--f9) / 2)',
            '10': 'calc(var(--f10) / 2)',
            '11': 'calc(var(--f11) / 2)',
            '12': 'calc(var(--f12) / 2)',
            '13': 'calc(var(--f13) / 2)',
            '14': 'calc(var(--f14) / 2)',
            '15': 'calc(var(--f15) / 2)',
            '16': 'calc(var(--f16) / 2)',
            '20': 'var(--f10)',
            '24': 'var(--f12)',
            '32': 'var(--f16)',
            '48': 'calc(var(--f16) * 2)',
            '64': 'calc(var(--f16) * 3)',
            '80': 'calc(var(--f16) * 4)',
            '96': 'calc(var(--f16) * 5)',
        },
        spacing: {
            '0': 0,
            '0.5': 'var(--f0)',
            '1': 'var(--f1)',
            '1.5': 'var(--f1_5)',
            '2': 'var(--f2)',
            '3': 'var(--f3)',
            'base': 'var(--f3)',
            '4': 'var(--f4)',
            '5': 'var(--f5)',
            '6': 'var(--f6)',
            '7': 'var(--f7)',
            '8': 'var(--f8)',
            '9': 'var(--f9)',
            '10': 'var(--f10)',
            '11': 'var(--f11)',
            '12': 'var(--f12)',
            '13': 'var(--f13)',
            '14': 'var(--f14)',
            '15': 'var(--f15)',
            '16': 'var(--f16)',
            '20': 'calc(var(--f10) * 2)',
            '24': 'calc(var(--f12) * 2)',
            '32': 'calc(var(--f16) * 2)',
            '48': 'calc(var(--f16) * 3)',
            '64': 'calc(var(--f16) * 4)',
            '80': 'calc(var(--f16) * 5)',
            '96': 'calc(var(--f16) * 6)',
        },
        borderRadius: {
            '0': 0,
            '0.5': 'var(--f0)',
            '1': 'var(--f1)',
            '2': 'var(--f2)',
            '3': 'var(--f3)',
            DEFAULT: 'var(--f3)',
            '4': 'var(--f4)',
            '5': 'var(--f5)',
            '6': 'var(--f6)',
            '7': 'var(--f7)',
            '8': 'var(--f8)',
            '9': 'var(--f9)',
            '10': 'var(--f10)',
            '11': 'var(--f11)',
            '12': 'var(--f12)',
            '13': 'var(--f13)',
            '14': 'var(--f14)',
            '15': 'var(--f15)',
            '16': 'var(--f16)',
            '20': 'calc(var(--f10) * 2)',
            '24': 'calc(var(--f12) * 2)',
            '32': 'calc(var(--f16) * 2)',
            '48': 'calc(var(--f16) * 3)',
            '64': 'calc(var(--f16) * 4)',
            '80': 'calc(var(--f16) * 5)',
            '96': 'calc(var(--f16) * 6)',
            'full': '9999px'
        },
        extend: {},
    },

    plugins: [],
}