#!/bin/bash
#------------------------------------------------------------------------------
# FILE:         setup-docker.sh
# CONTRIBUTOR:  Jeff Lill
# COPYRIGHT:    Copyright (c) 2005-2020 by neonFORGE, LLC.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This script must be run under [sudo].
#
# NOTE: Variables formatted like $<name> will be expanded by [neon-cli]
#       using a [PreprocessReader].
#
# This script handles the installation of the Docker CLI.

# Configure Bash strict mode so that the entire script will fail if 
# any of the commands fail.
#
#       http://redsymbol.net/articles/unofficial-bash-strict-mode/

set -euo pipefail

echo
echo "**********************************************" 1>&2
echo "** SETUP-DOCKER                             **" 1>&2
echo "**********************************************" 1>&2

# Load the cluster configuration and setup utilities.

. $<load-cluster-conf>
. setup-utility.sh

# Ensure that setup is idempotent.

startsetup docker

#--------------------------------------------------------------------------
# Note we're going to delete the docker unique key file if present.  Docker will
# generate a unique key the first time it starts.  It's possible that a key
# might be left over if the OS image was cloned.  Docker Swarm won't schedule
# containers on nodes with duplicate keys.

rm -f /etc/docker/key.json

#--------------------------------------------------------------------------
# We want the Docker containers, volumes, and other files to be located on
# the attached data drive (if there is one) rather than the OS drive.  Node
# preparation should have configured [/mnt-data] to be a link to the data
# drive or simply be a physical directory on the OS drive so we'll link
# the root Docker storage directory [/var/lib/docker] to [/mnt-data/docker]

if [ ! -d /mnt-data/docker ] ; then
	mkdir -p /mnt-data/docker
	ln -s /mnt-data/docker /var/lib/docker
fi

#--------------------------------------------------------------------------
# Install Kubernetes (and other) prerequisites.

safe-apt-get install -yq --allow-downgrades curl apt-transport-https ca-certificates 

#--------------------------------------------------------------------------
# Install Docker
#
#   https://docs.docker.com/engine/installation/linux/ubuntulinux/

# Install additional Docker prerequisites.  We need to do this manually  because the 
# [gdebi] command executed below doesn't do this.

safe-apt-get install -yq --allow-downgrades software-properties-common

# Download the Docker GPG key.

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

# Configure the stable repository only.  We don't currently support specifying a 
# specific edge or testing release.

add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
safe-apt-get update

# Download and install the Docker package.

docker_package_uri=$<docker.packageuri>
curl ${CURL_RETRY} ${docker_package_uri} -o /tmp/docker.deb
gdebi --non-interactive /tmp/docker.deb
rm /tmp/docker.deb

#--------------------------------------------------------------------------
# Setup the Docker config file.

cat > /etc/docker/daemon.json <<EOF
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
EOF

chmod 664 /etc/docker/daemon.json

#--------------------------------------------------------------------------
# Create a drop-in Docker systemd unit file that has our custom options.

cat <<EOF > /etc/systemd/system/docker.service
# Modified from the original installed by Docker to add custom command
# line options generated by [neon-cli] as well as explicit restart options.

[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target
After=
Requires=
Before=

[Service]
Type=notify
# The default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd --data-root /mnt-data/docker $<docker.options>
ExecReload=/bin/kill -s HUP \$MAINPID
# Rate limit Docker restarts
Restart=always
RestartSec=2s
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0
# Set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# Kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target
EOF

# We need to do a [daemon-reload] so systemd will be aware of the new unit drop-in.

systemctl disable docker
systemctl daemon-reload

# Configure Docker to start on boot and then restart it to pick up the new options.

systemctl enable docker
systemctl restart docker

# We relocated the Docker graph root directory to [/mnt-data/docker] so we can
# remove any of the old files at the default location.

if [ -d /var/lib/docker ] ; then
	rm -r /var/lib/docker
fi

# Prevent the package manager from automatically upgrading the Docker engine.

set +e      # Don't exit if the next command fails
apt-mark hold docker

# Indicate that the script has completed.

endsetup docker
