//-----------------------------------------------------------------------------
// FILE:        HeadendClient.cs
// CONTRIBUTOR: Jeff Lill
// COPYRIGHT:   Copyright © 2005-2023 by NEONFORGE LLC.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Net.Http;

using Neon.Common;
using Neon.Retry;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Serialization;

using YamlDotNet.Serialization;

namespace Neon.Kube.Clients
{
    /// <summary>
    /// Extends the <see cref="HeadendClient"/> class generated by <b>modelgen</b>
    /// with static creation methods.
    /// </summary>
    public partial class HeadendClient
    {
        /// <summary>
        /// Creates a <see cref="HeadendClient"/>.
        /// </summary>
        /// <param name="baseAddress">
        /// Optionally specifies the base URI for the client.  This defaults to the
        /// headend service URI returned by <see cref="KubeEnv.HeadendUri"/>.
        /// </param>
        /// <param name="retryPolicy">Optionally specifies a default retry policy (defaults to <see cref="NoRetryPolicy"/>).</param>
        /// <returns>The new <see cref="HeadendClient"/>.</returns>
        public static HeadendClient Create(Uri baseAddress = null, IRetryPolicy retryPolicy = null)
        {
            baseAddress ??= KubeEnv.HeadendUri;

            return new HeadendClient(new HttpClient() { BaseAddress = baseAddress }, retryPolicy);
        }
    }
}
