//-----------------------------------------------------------------------------
// FILE:	    DnsAnswers.cs
// CONTRIBUTOR: Jeff Lill
// COPYRIGHT:	Copyright (c) 2016-2018 by neonFORGE, LLC.  All rights reserved.

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.Contracts;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Serialization;

using Neon.Net;
using System.Net;

namespace Neon.Cluster
{
    /// <summary>
    /// Holds the the DNS answers generated by the <b>neon-dns-mon</b> service.
    /// </summary>
    public class DnsAnswers
    {
        private int     ttl;

        /// <summary>
        /// Returns the current list of DNS answers.
        /// </summary>
        [JsonProperty(PropertyName = "Answers", Required = Required.Always)]
        public List<DnsAnswer> Answers { get; set; } = new List<DnsAnswer>();

        /// <summary>
        /// The DNS TTL in seconds.
        /// </summary>
        [JsonProperty(PropertyName = "Ttl", Required = Required.Always)]
        public int Ttl
        {
            get { return ttl; }

            set
            {
                Covenant.Requires<ArgumentException>(value >= 0, $"DNS [TTL={value}] is not valid.");

                ttl = value;
            }
        }
    }
}
