//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deployer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deployer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] agent_address {
            get {
                object obj = ResourceManager.GetObject("agent_address", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cassandra {
            get {
                object obj = ResourceManager.GetObject("cassandra", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cassandra_commitlog_archiving {
            get {
                object obj = ResourceManager.GetObject("cassandra_commitlog_archiving", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cassandra_env {
            get {
                object obj = ResourceManager.GetObject("cassandra_env", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cassandra_init {
            get {
                object obj = ResourceManager.GetObject("cassandra_init", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cassandra_initd {
            get {
                object obj = ResourceManager.GetObject("cassandra_initd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        /// Licensed to the Apache Software Foundation (ASF) under one
        /// or more contributor license agreements.  See the NOTICE file
        /// distributed with this work for additional information
        /// regarding copyright ownership.  The ASF licenses this file
        /// to you under the Apache License, Version 2.0 (the
        /// &quot;License&quot;); you may not use this file except in compliance
        /// with the License.  You may obtain a copy of the License at
        ///
        ///   http://www.apache.org/licenses/LICENSE-2.0
        ///
        /// Unless required by applicable law or ag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cassandra_logback {
            get {
                return ResourceManager.GetString("cassandra_logback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        /// Licensed to the Apache Software Foundation (ASF) under one
        /// or more contributor license agreements.  See the NOTICE file
        /// distributed with this work for additional information
        /// regarding copyright ownership.  The ASF licenses this file
        /// to you under the Apache License, Version 2.0 (the
        /// &quot;License&quot;); you may not use this file except in compliance
        /// with the License.  You may obtain a copy of the License at
        ///
        ///   http://www.apache.org/licenses/LICENSE-2.0
        ///
        /// Unless required by applicable law or ag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cassandra_logback_tools {
            get {
                return ResourceManager.GetString("cassandra_logback_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cassandra_opscenter_cluster {
            get {
                object obj = ResourceManager.GetObject("cassandra_opscenter_cluster", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cassandra_opscenterd {
            get {
                object obj = ResourceManager.GetObject("cassandra_opscenterd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cassandra_rackdc {
            get {
                object obj = ResourceManager.GetObject("cassandra_rackdc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] elasticsearch_init {
            get {
                object obj = ResourceManager.GetObject("elasticsearch_init", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] elasticsearch_logging_yml {
            get {
                object obj = ResourceManager.GetObject("elasticsearch_logging_yml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] elasticsearch_yml {
            get {
                object obj = ResourceManager.GetObject("elasticsearch_yml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] kibana {
            get {
                object obj = ResourceManager.GetObject("kibana", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] kibana_init {
            get {
                object obj = ResourceManager.GetObject("kibana_init", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] log_processor {
            get {
                object obj = ResourceManager.GetObject("log_processor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] logstash_init {
            get {
                object obj = ResourceManager.GetObject("logstash_init", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mongoc {
            get {
                object obj = ResourceManager.GetObject("mongoc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mongoc_init {
            get {
                object obj = ResourceManager.GetObject("mongoc_init", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mongod {
            get {
                object obj = ResourceManager.GetObject("mongod", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mongod_init {
            get {
                object obj = ResourceManager.GetObject("mongod_init", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mongos {
            get {
                object obj = ResourceManager.GetObject("mongos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mongos_init {
            get {
                object obj = ResourceManager.GetObject("mongos_init", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] nginx {
            get {
                object obj = ResourceManager.GetObject("nginx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ntp {
            get {
                object obj = ResourceManager.GetObject("ntp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] patch_mongo {
            get {
                object obj = ResourceManager.GetObject("patch_mongo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] redis {
            get {
                object obj = ResourceManager.GetObject("redis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] redis_initd {
            get {
                object obj = ResourceManager.GetObject("redis_initd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] service_starter {
            get {
                object obj = ResourceManager.GetObject("service_starter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_agent {
            get {
                object obj = ResourceManager.GetObject("setup_agent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_cassandra {
            get {
                object obj = ResourceManager.GetObject("setup_cassandra", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_cdb {
            get {
                object obj = ResourceManager.GetObject("setup_cdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_clean {
            get {
                object obj = ResourceManager.GetObject("setup_clean", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_cops {
            get {
                object obj = ResourceManager.GetObject("setup_cops", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_disk {
            get {
                object obj = ResourceManager.GetObject("setup_disk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_dotnet {
            get {
                object obj = ResourceManager.GetObject("setup_dotnet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_elasticsearch {
            get {
                object obj = ResourceManager.GetObject("setup_elasticsearch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_esd {
            get {
                object obj = ResourceManager.GetObject("setup_esd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_esr {
            get {
                object obj = ResourceManager.GetObject("setup_esr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_hosts {
            get {
                object obj = ResourceManager.GetObject("setup_hosts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_java {
            get {
                object obj = ResourceManager.GetObject("setup_java", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_linux {
            get {
                object obj = ResourceManager.GetObject("setup_linux", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_logstash {
            get {
                object obj = ResourceManager.GetObject("setup_logstash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_mdb {
            get {
                object obj = ResourceManager.GetObject("setup_mdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_mongo {
            get {
                object obj = ResourceManager.GetObject("setup_mongo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_mongo_admin {
            get {
                object obj = ResourceManager.GetObject("setup_mongo_admin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_mqr {
            get {
                object obj = ResourceManager.GetObject("setup_mqr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_nginx_passwd {
            get {
                object obj = ResourceManager.GetObject("setup_nginx_passwd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_ntp {
            get {
                object obj = ResourceManager.GetObject("setup_ntp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_rds {
            get {
                object obj = ResourceManager.GetObject("setup_rds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_redis {
            get {
                object obj = ResourceManager.GetObject("setup_redis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_tdb {
            get {
                object obj = ResourceManager.GetObject("setup_tdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_toku_admin {
            get {
                object obj = ResourceManager.GetObject("setup_toku_admin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_tokumx {
            get {
                object obj = ResourceManager.GetObject("setup_tokumx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setup_tqr {
            get {
                object obj = ResourceManager.GetObject("setup_tqr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tokumxc {
            get {
                object obj = ResourceManager.GetObject("tokumxc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tokumxc_init {
            get {
                object obj = ResourceManager.GetObject("tokumxc_init", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tokumxd {
            get {
                object obj = ResourceManager.GetObject("tokumxd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tokumxd_init {
            get {
                object obj = ResourceManager.GetObject("tokumxd_init", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tokumxs {
            get {
                object obj = ResourceManager.GetObject("tokumxs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tokumxs_init {
            get {
                object obj = ResourceManager.GetObject("tokumxs_init", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] unpatch_mongo {
            get {
                object obj = ResourceManager.GetObject("unpatch_mongo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] upgrade_linux {
            get {
                object obj = ResourceManager.GetObject("upgrade_linux", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] upgrade_shards {
            get {
                object obj = ResourceManager.GetObject("upgrade_shards", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
