#------------------------------------------------------------------------------
# FILE:         Dockerfile
# CONTRIBUTOR:  Jeff Lill
# COPYRIGHT:    Copyright © 2005-2024 by NEONFORGE LLC.  All rights reserved.
#
# The contents of this repository are for private use by NEONFORGE, LLC. and may not be
# divulged or used for any purpose by other organizations or individuals without a
# formal written and signed agreement with NEONFORGE, LLC.

ARG         VERSION
FROM        registry.k8s.io/coredns/coredns:${VERSION}
MAINTAINER  jeff@lill.io
STOPSIGNAL  SIGTERM
