//-----------------------------------------------------------------------------
// FILE:	    IDynamicDocument.cs
// CONTRIBUTOR: Jeff Lill
// COPYRIGHT:	Copyright (c) 2016-2019 by neonFORGE, LLC.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;

using Neon.Common;
using Neon.DynamicData;

namespace Neon.DynamicData
{
    /// <summary>
    /// Base interface for document classes generated by the <b>gen-entity</b>
    /// tool.
    /// </summary>
    public interface IDynamicDocument
    {
        /// <summary>
        /// Returns the document's link string.
        /// </summary>
        /// <returns>The link string or <c>null</c>.</returns>
        /// <remarks>
        /// <see cref="_GetLink()"/> is used to implement entity linking for environments that
        /// provide an <see cref="IDynamicEntityContext"/> implementation.
        /// </remarks>
        string _GetLink();

        /// <summary>
        /// Returns <c>true</c> if the document has been deleted.
        /// </summary>
        bool IsDeleted { get; }
    }
}
