//-----------------------------------------------------------------------------
// FILE:	    SimpleMapper.cs
// CONTRIBUTOR: Jeff Lill
// COPYRIGHT:	Copyright (c) 2016-2017 by NeonForge, LLC.  All rights reserved.

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.Contracts;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;

using Neon.Common;
using Neon.Data;

namespace Neon.Data.Internal
{
    /// <summary>
    /// <b>Platform use only:</b> Used by <see cref="IEntity"/> implementations 
    /// to map entity properties with a simple single value to their underlying
    /// <see cref="JProperty"/>.
    /// </summary>
    /// <typeparam name="TValue">The property value type.</typeparam>
    /// <remarks>
    /// <note>
    /// This class is intended for use only by classes generated by the 
    /// <b>entity-gen</b> build tool.
    /// </note>
    /// </remarks>
    /// <threadsafety instance="false"/>
    public struct SimpleMapper<TValue> : IPropertyMapper
    {
        private IEntity             parentEntity;
        private IEntityContext      context;
        private JProperty           property;

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="parentEntity">The <see cref="IEntity"/> that owns this mapper.</param>
        /// <param name="jsonName">The JSON property name.</param>
        /// <param name="propertyName">The entity property name.</param>
        /// <param name="context">The <see cref="IEntityContext"/> or <c>null</c>.</param>
        public SimpleMapper(IEntity parentEntity, string jsonName, string propertyName, IEntityContext context)
        {
            Covenant.Requires<ArgumentNullException>(parentEntity != null);
            Covenant.Requires<ArgumentNullException>(!string.IsNullOrEmpty(jsonName));
            Covenant.Requires<ArgumentNullException>(!string.IsNullOrEmpty(propertyName));

            this.parentEntity = parentEntity;
            this.context      = context;
            this.JsonName     = jsonName;
            this.PropertyName = propertyName;
            this.property     = null;
        }

        /// <inheritdoc/>
        public string JsonName { get; private set; }

        /// <inheritdoc/>
        public string PropertyName { get; private set; }

        /// <summary>
        /// The current property value.
        /// </summary>
        public TValue Value
        {
            get { return property.Value.ToObject<TValue>(); }
            set { property.Value = value != null ? JToken.FromObject(value) : null; }
        }

        /// <inheritdoc/>
        public bool Load(JProperty newProperty, bool reload = false)
        {
            Covenant.Requires<ArgumentNullException>(newProperty != null);

            var changed = !NeonHelper.JTokenEquals(property, newProperty);

            NeonHelper.JTokenEquals(property, newProperty);

            property = newProperty;

            if (reload && changed)
            {
                parentEntity._OnPropertyChanged(PropertyName);
            }

            return changed;
        }
    }
}
